### ISSUE TITLE
Question about skip_frame.

### ISSUE THREAD

**Issue by YTEP-ZHI** [EDiRobotics/GR1-Training#1]
Hi @StarCycle, thanks for contributing to reproducing the training code of GR-1. I have two questions regarding the `skip_frame`.
* What's the meaning of this parameter and why setting it to 3 in config:
https://github.com/EDiRobotics/GR1-Training/blob/6670d3c970d17acefe894c827555fa2f1f443a63/configs.json#L44

It seems that the first 3 frames in each predicted sequence will not be supervised, but why should we ignore these frames?

* Why are the slicing strategies of `new_pred` and `new_target` different? Shouldn't they be treated in the same way?
https://github.com/EDiRobotics/GR1-Training/blob/6670d3c970d17acefe894c827555fa2f1f443a63/Main.py#L27-L29

Looking forward to your reply.

**Comment by StarCycle** [comment]
Hi @YTEP-ZHI,

- What's the meaning of this parameter and why setting it to 3 in config:

Please refer to this [issue](https://github.com/bytedance/GR-1/issues/6).

- Why are the slicing strategies of new_pred and new_target different? Shouldn't they be treated in the same way?

It's the same as the first question. Assuming we have a sequence with 10 frames, then we let the model to predict that last 7 frames based on the first 7 frame. In this case ∆t = 3 (as mentioned in appendix A.4 in their paper).

I am still working on varients of GR1. You are welcomed to join the wechat group (I will update the QR code now)!

Best,
StarCycle

**Comment by StarCycle** [comment]
@YTEP-ZHI Now I update the QR code!

**Comment by YTEP-ZHI** [comment]
@StarCycle Thank you for your quick and insightful reply.
